views/site.py
from flask import Blueprint, render_template, url_for, g

from core.wrappers import user

import barcode

bp = Blueprint('site', __name__)

@bp.route('/')
@user
def index():
    menu = [
        {
            'name': 'Speakers',
            'link': url_for('site.speakers'),
            'icon': 'fas fa-graduation-cap'
        },{
            'name': 'Forum',
            'link': '/forum',
            'icon': 'fas fa-exchange-alt'
        },{
            'name': 'Competitions',
            'link': url_for('site.competitions'),
            'icon': 'fas fa-trophy'
        },{
            'name': 'Message',
            'link': url_for('site.message'),
            'icon': 'fas fa-comments'
        },{
            'name': 'Barcode',
            'link': url_for('site.barcode_image'),
            'icon': 'fas fa-barcode'
        },{
            'name': 'Facebook',
            'link': 'https://facebook.com/feutechscc',
            'icon': 'fab fa-facebook'
        },{
            'name': 'Twitter',
            'link': 'https://twitter.com/feutechscc',
            'icon': 'fab fa-twitter'
        }
    ]
    return render_template('index.html', menu_icons=menu)

@bp.route('/barcode')
@user
def barcode_image():
    return render_template('barcode.html')

@bp.route('/speakers')
@user
def speakers():
    speaker = []


    speaker.append({
        'img': url_for('static', filename='img/speakers/0.jpg'),
        'name': 'Ludwig Feredigan',
        'description': 'Climate Reality Leader of The Climate Reality Project, Philippines',
        'link': url_for('site.profile', id='0')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/1.png'),
        'name': 'Rindu Alriavindrafunny',
        'description': 'Lecturer of Institute Technology Adisutjipto',
        'link': url_for('site.profile', id='1')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/2.jpg'),
        'name': 'Dr. Manuel Belino',
        'description': 'Senior Director for Engineering of FEU Institute of Technology',
        'link': url_for('site.profile', id='2')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/3.jpg'),
        'name': 'Yacine Petitprez',
        'description': 'IT Manager of Ingedata International',
        'link': url_for('site.profile', id='3')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/4.jpg'),
        'name': 'Arlene Romasanta',
        'description': 'OIC, Systems and Infrastructure Development Service (SID) of Department of Information and Communication Technology',
        'link': url_for('site.profile', id='4')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/5.jpg'),
        'name': 'Dr. Michael Choy Seng Kim',
        'description': 'Founder of Dioworks Learning',
        'link': url_for('site.profile', id='5')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/6.png'),
        'name': 'Dr. Alberto Amorsolo',
        'description': 'Professor of UP College of Engineering',
        'link': url_for('site.profile', id='6')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/7.jpg'),
        'name': 'Neil Stephen Lopez',
        'description': 'Assistant Professor, Vice Chair and External Affairs Coordinator, Mechanical Engineering of De La Salle University',
        'link': url_for('site.profile', id='7')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/8.jpg'),
        'name': 'Dr. Rosemary Vesa',
        'description': 'President of the Human Factors and Ergonomics Society of the Philippines, Philippines',
        'link': url_for('site.profile', id='8')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/9.jpg'),
        'name': 'Atty. Analiza Rebuelta-Teh',
        'description': 'Interim Undersecretary for Mining of Department of Environment and Natural Resources (DENR), Philippines',
        'link': url_for('site.profile', id='9')
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/10.jpg'),
        'name': 'Virgilio Leyba',
        'description': 'Information and Technology Services Department Manager of National Power Corporation, Philippines',
        'link': url_for('site.profile', id='10')
    })
    return render_template('speakers.html', speaker=speaker)

@bp.route('/profile/<int:id>')
@user
def profile(id):
    speaker = [];

    speaker.append({
        'img': url_for('static', filename='img/speakers/0.jpg'),
        'name': 'Ludwig Feredigan',
        'description': 'Climate Reality Leader of The Climate Reality Project, Philippines',
        'summary': [
            'Graduate of Bachelor of Science in Engineering major in Electronics & Communications (BSECE) at the Don Bosco Technical College',
            'Graduate of Masters in Business Administration at the University of San Carlos of Cebu City',
            'Strategic Business Economic Program graduate at the University of Asia & the Pacific',
            'Finished diploma in Supply Chain Management under the Business & Training Linkage Program of the PUM Entrepreneurs for Entrepreneurs at the Hague Netherlands',
            'Recipient of a number of fellowships and scholarships on executive development programs on climate change, sustainable consumption and production, green energy and climate finance, and leadership',
            'Expert Reviewers on the first order draft of the Intergovernmental Panel on Climate Change (IPCC) Special Report on Global Warming of 1.5ºC (SR15)',
            'Miguel R. Magalang Individual Climate Leadership Memorial Awardee given by The Climate Reality Project Philippines',
            'Dangal ng Kalikasan Awardee given by the Mister Earth Philippines'
        ]
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/1.png'),
        'name': 'Rindu Alriavindrafunny',
        'description': 'Lecturer of Institute Technology Adisutjipto',
        'summary': [
            'Masters degree on Mathematics Education in State University of Surabaya',
            'Masters degree on Science Education Communication and Technology (SECT), Utrecht University, Utrecht Belanda',
            'Instructor of Elementary, Middle School, and Senior High School in the different schools in Indonesia',
            'Mathematics Lecturer of the Aeronatica Engineering Department and the Head of Student Affairs of Institute of Technology Adisutjpto, Yogyakarta, Indonesia',
            'Master Course in Science Education Communication and Technology (SECT), Utrecht University, Utrecht Belanda'
        ]
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/2.jpg'),
        'name': 'Dr. Manuel Belino',
        'description': 'Senior Director for Engineering of FEU Institute of Technology',
        'summary': [
            'Bachelor’s degree in Mechanical Engineering, Mapua Institute of Technology, Philippines',
            'Masters degree in Engineering Education, De La Salle University. Philippines',
            'Master’s degree of Theological Studies, Havard University, USA',
            'Doctorate degree in Religious and Values Education, De La Salle University',
            'Chair of the Commission on Higher Education (CHED) Technical Committee in Mechanical Engineering',
            'Published in local and international journals in the fields of engineeting ethics, engineering education and safety engineering',
            'Featured in the Metrobank 50th anniversary publication Ten Outstanding Filipino Teachers',
            'President, Philippine Institute of Mechanical Engineering Educators',
            'Senior Director for Engineering,Far Eastern University Institute of Technology'
        ]
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/3.jpg'),
        'name': 'Yacine Petitprez',
        'description': 'IT Manager of Ingedata International',
        'summary': [
            'IT Manager, Ingedata Philippines',
            'Founder and Chief Operating Officer of the Digital Bakery LTD., Philippines',
            'IT Consultant of Iscale, Philippines an Web application factory, focused on delivering custom made applications for international customers',
            'Trainer of the programming language, Ruby on Rails in France in year 2013'
        ]
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/4.jpg'),
        'name': 'Arlene Romasanta',
        'description': 'OIC, Systems and Infrastructure Development Service (SID) of Department of Information and Communication Technology',
        'summary': [
            'Bachelor of Science in Computer Data Processing Management, Polytechnic University of the Philippines',
            'Master’s degree in Productivity and Quality Management with Leadership Award, Development Academy of the Philippines',
            'Took international course, “Formulating and Managing GIS Projects” at the International Institute for Geo-Information Science and Earth Observation, Enschede, The Netherlands',
            'Co-Project Lead in the International Collaborative Research on Disaster Response Model Using Vehicle Communications that was funded by Asia Pacific Telecommunity',
            'OIC Director of the Systems and Infrastructure Development Service, Department of Information and Communications Technology (DICT)',
            'Division Chief/Information Technology Officer 3, Strategic R&D Services Division (SRDSD) Systems and Infrastructure Development Service (SIDS), DICT'
        ]
    })
    speaker.append({
        'img': url_for('static', filename='img/speakers/5.jpg'),
        'name': 'Dr. Michael Choy Seng Kim',
        'description': 'Founder of Dioworks Learning',
        'summary': [

views/users.py
from flask import Blueprint, render_template, redirect, session, request, url_for, flash

from core.wrappers import guest, user

import requests

bp = Blueprint('users', __name__)

@bp.route('/login', methods=['GET', 'POST'])
@guest
def login():
    error = None
    if request.method == 'POST':
        payload = {'email_address': request.form.get('email_address')}
        user_data = requests.get('http://feutech.edu.ph/scc/api/tf/get_participant', params=payload).json().get('data')
        if user_data:
            session['user'] = user_data
            flash("Welcome to 1st International TechnoFest, {}!".format(user_data.get('first_name')))
            return redirect(url_for('site.index'))
        else:
            error = 'You are not registred to TechnoFest'
    return render_template('login.html', error=error)

@bp.route('/logout', methods=['POST'])
@user
def logout():
    session.pop('user')
    return redirect(url_for('users.login'))

templates/barcode.html
{% extends 'base.html' %}

{% block title %} | Barcode{% endblock %}

{% block nav_title %}Barcode{% endblock %}

{% block background %}{{ url_for('static', filename='img/bg/bg-md-3.png') }}{% endblock %}

{% block content %}
<div class="container h-100">
    <div class="row justify-content-center align-items-center align-content-center h-100">
        <div class="col-12">
            <div id="barcode" class="d-block text-center mb-4"></div>
        </div>
        <div class="col-12">
            <h6 class="text-center mb-2">Use this for your attendance.</h6>
            <h6 class="text-center">ID: <span class="font-weight-bold">{{ g.user.get('id') }}</span></h6>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $.ajax({
        url: '/api/get_barcode',
        type: 'GET'
    }).done(function(data) {
        $('#barcode').html(data);
    });
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://bootswatch.com/4/united/bootstrap.min.css" type="text/css"> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block css %}
    {% endblock %}

    <title>TechnoFest Portal{% block title %}{% endblock %}</title>
</head>
<body class="full-page" style="overflow: hidden;">
    {% block splashscreen %}
    <div id="load" class="h-100 w-100 position-fixed bg-white">
        <div class="d-flex align-content-center w-100 h-100">
            <!-- <img src="{{ url_for('static', filename='img/icon/load.png') }}" class="img-fluid d-block mx-auto align-self-center" style="width: 150px;"> -->
            <img src="{{ url_for('static', filename='img/icon/load.gif') }}" class="img-fluid d-block mx-auto align-self-center" style="width: 20rem;">
        </div>
    </div>
    {% endblock %}
    
    {% block body %}
    <div class="fixed-top d-flex flex-column h-100 w-100" style="background-image: url('{% block background %}{% endblock %}'); background-position: center; background-size: cover; overflow: hidden;">
        {% block nav %}
        <div class="d-block bg-success py-2 px-3" style="box-shadow: 0px 2px 5px #000; z-index: 1;">
            {% block nav_content %}
            <div class="row align-items-center">
                <div class="col-2">
                    {% if 'user' in session %}
                    <a href="{% block return_link %}{{ url_for('site.index') }}{% endblock %}" class="btn btn-link text-white">
                        <i class="fa fa-arrow-left" style="font-size: 1.5em;"></i>
                    </a>
                    {% endif %}
                </div>
                <div class="col-8">
                    <h4 class="text-warning font-weight-bold text-uppercase text-center mb-0" style="text-shadow: 0px 2px 4px #000;">{% block nav_title %}{% endblock %}</h4>
                </div>
            </div>
            {% endblock %}
        </div>
        {% endblock %}
        
        {% block content_override %}
        <div class="d-block h-100 py-3" style="overflow-x: auto;">
            {% block content %}
            {% endblock %}
        </div>
        {% endblock %}
    </div>
    {% endblock %}
    
    <div id="notifContainer" class="fixed-top w-100 pt-2 px-3" style="z-index: 9999; display: none;">
        {% block notif %}
        {% endblock %}
    </div>

    {% block modal %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script>
        requestFullScreen(document.body);
    </script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/competitions.html
{% extends 'base.html' %}

{% block title %} | Competition{% endblock %}

{% block background %}{{ url_for('static', filename='img/bg/bg-3.png') }}{% endblock %}

{% block nav_title %}Competitions{% endblock %}

{% block content %}
<div class="container">
    <div class="row align-items-center">
        {% for i in competition %}
        <div class="col-12 col-md-6 mb-3">
            <div class="card border-0 shadow">
                <div class="card-header bg-success" data-target="#competition{{ loop.index }}" data-toggle="collapse">
                    <img class="img-fluid" src="{{ i['img'] }}" alt="">
                </div>
                <div id="competition{{ loop.index }}" class="collapse">
                    <div class="card-body">
                        <blockquote class="blockquote">
                        <p class="small mb-0">{{ i['description'] }}</p>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/forum.html
{%extends 'base.html' %}

{% block title %} | Forum{% endblock %}

{% block nav_title %}Forum{% endblock %}

{% block background %}{{ url_for('static', filename='img/bg/bg-3.png') }}{% endblock %}

{% block modal %}
<div class="modal fade" id="askModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <form id="askForm" onsubmit="submit_question(event)">
                <div class="modal-header border-0 bg-success text-white">
                    <h5 class="modal-title font-weight-bold">Ask a Question</h5>
                </div>
                <div class="modal-body bg-success text-white">
                    <div class="form-group mb-2">
                        <label for="questionField" class="font-weight-bold">Question</label>
                        <input type="text" id="questionField" name="question" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="receiverField" class="font-weight-bold">for</label>
                        <select id="receiverField" name="receiver" class="custom-select">
                            <option value="All">All</option>
                            {% for i in speakers %}
                            <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="custom-control custom-checkbox d-none">
                        <input type="checkbox" id="senderAnonymousCheckbox" name="sender_anonymous" class="custom-control-input" value="true">
                        <label class="custom-control-label" for="senderAnonymousCheckbox">Send question anonymously</label>
                    </div>
                </div>
                <div class="modal-footer border-0 bg-warning">
                    <button type="submit" class="btn btn-success">Ask Question</button>
                    <button class="btn btn-dark" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row align-items-center">
        <div class="col-12 mb-3 py-2">
            <button class="btn btn-warning btn-block bg-lg font-weight-bold shadow" data-target="#askModal" data-toggle="modal">Ask a Question</button>
        </div>
        <div class="col-12">
            <div id="forumContainer" class="card-columns"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    function submit_question(e) {
        e.preventDefault();

        $.ajax({
            url: '/api/ask_question',
            type: 'POST',
            data: $('#askForm').serializeArray()
        }).done(function(data) {
            if(data['status']) {
                $('#askForm')[0].reset();
                $('#askModal').modal('hide');
                notif_alert('Your question is successfully submitted', 'success');
            } else {
                notif_alert('Failed submitting question', 'warning');
            }
        }).fail(function(data) {
            notif_alert('Failed submitting question', 'warning');
        });
    }

    function vote_question(e) {
        e.preventDefault()

        $.ajax({
            url: '/api/vote_question',
            type: 'POST',
            data: {
                id: $(e.target).closest('.card').attr('data-value')
            }
        }).done(function(data) {
            if(data['status']) {
                $(e.target).closest('.card').find('.question-votes').html(data['count']);
                notif_alert('Question voted successfully', 'success');
            } else {
                notif_alert(data['error'], 'warning');
            }
        }).fail(function(data) {
            notif_alert('Question vote fail', 'warning');
        });
    }

    function render_card(data) {
        return `<div class="card bg-success text-white border-0 shadow" data-value="${data['id']}">
            <div class="card-header">
                <h5 class="mb-0"><span class="question-votes font-weight-bold h3">${data['vote_count']}</span> votes</h5>
            </div>
            <div class="card-body">
                <h5 class="card-title">${data['question']}</h5>
                <p class="card-text">For ${data['receiver']}</p>
            </div>
            <div class="card-footer bg-warning">
                <button class="btn btn-success btn-block" onclick="vote_question(event)">Vote</button>
            </div>
        </div>`;
    }

    $(function() {
        // $('#askModal').modal('show');
        $.ajax({
            url: '/api/get_questions',
            type: 'GET',
            dataType: 'JSON'
        }).done(function(data) {
            data.forEach(function(value, index) {
                $('#forumContainer').prepend(render_card(value));
            });
        });
    });
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %} | Home{% endblock %}

{% block background %}{{ url_for('static', filename='img/bg/bg-md-2.png') }}{% endblock %}

{% block nav_content %}
<h4 class="text-warning font-weight-bold mb-0" style="text-shadow: 0px 2px 4px #000;">TECHNOFEST 2018</h4>
<h6 class="text-white font-weight-bold mb-0">PERSONAL ASSISTANT</h6>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center h-100 w-100">
    <div class="container h-100">
        <div class="row px-3">
            {% for x in menu_icons %}
            <div class="col-4 mb-3 px-2">
                <a href="{{ x['link'] }}" class="btn btn-success btn-block btn-lg menu-btn text-white text-center shadow p-3 mb-1">
                    <i class="{{ x['icon'] }}" style="font-size: 2.5rem;"></i>
                </a>
                <span class="d-block small text-center font-weight-bold text-truncate">{{ x['name'] }}</span>
            </div>
            {% endfor %}
            <div class="col-4 mb-3 px-2">
                <form action="{{ url_for('users.logout') }}" method="post">
                    <button type="submit" class="btn btn-success btn-block btn-lg menu-btn text-white text-center shadow p-3 mb-1" >
                        <i class="fas fa-sign-out-alt" style="font-size: 2.5rem;"></i>
                    </button>
                    <span class="d-block small text-center font-weight-bold text-truncate">Log out</span>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <script>notif_alert('{{ messages.pop() }}', 'success')</script>
        {% endif %}
    {% endwith %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %} | Login{% endblock %}

{% block nav %}{% endblock %}

{% block background %}{{ url_for('static', filename='img/bg/bg-1.png') }}{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center h-100 w-100">
    <div class="container">
        <div class="d-flex d-md-none flex-column justify-content-center align-content-around h-100">
            <img class="d-block img-fluid mx-auto mb-2" src="{{ url_for('static', filename='img/logo/logo-white.png') }}" alt="Logo">
            <h6 class="text-uppercase font-weight-bold text-center text-white mb-3">April 25 - 27, 2018</h6>
            <h4 class="text-uppercase font-weight-bold text-center text-warning mb-5" style="text-shadow: 0px 4px 5px #000;">Personal Assistant</h4>
            <form class="mb-4" action="{{ url_for('users.login') }}" method="post">
                <p class="text-white font-weight-bold text-uppercase text-center mt-3">Log in to your account</p>
                <div class="form-group mb-3">
                    <input class="form-control custom-input-text border-0" type="email" name="email_address" id="emailAddressField" placeholder="Email Address" style="border-radius: 1rem;">
                    {% if error %}
                        <div class="form-text text-white">{{ error }}</div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-success btn-block">Log in</button>
            </form>
            <p class="text-white text-center small">&copy; 2018 Far Eastern University Institute of Technology | Student Coordinating Council</p>
        </div>

        <div class="d-none d-md-flex justify-content-center align-items-center align-content-center h-100">
            <div class="d-block w-50">
                <img class="d-block img-fluid mx-auto mb-5" src="{{ url_for('static', filename='img/logo/logo-white.png') }}" alt="Logo">
                <div class="card card-body bg-light px-4 px-3 mb-3">
                    <form action="{{ url_for('users.login') }}" method="post">
                        <p class="text-dark font-weight-bold text-uppercase text-center">Log in to your account</p>
                        <div class="form-group mb-3">
                            <input class="form-control bg-dark text-white custom-input-text border-0" type="email" name="email_address" id="emailAddressField" placeholder="Email Address" style="border-radius: 1rem;">
                            {% if error %}
                                <div class="form-text text-white">{{ error }}</div>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-success btn-block">Log in</button>
                    </form>
                </div>
                <p class="text-white text-center small">&copy; 2018 Far Eastern University Institute of Technology | Student Coordinating Council</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/message.html
{% extends 'base.html' %}

{% block title %} | Message{% endblock %}

{% block nav_title %}Message{% endblock %}

{% block background %}{{ url_for('static', filename='img/bg/bg-3.png') }}{% endblock %}

{% block content_override %}
<div class="d-block h-100 w-100" style="overflow: hidden;">
<div class="d-flex flex-column h-100 w-100" style="overflow: hidden;">

<div id="inboxContainer" class="d-block h-100 w-100 p-3" style="overflow-y: auto;">
    <div id="inbox" class="d-block w-100">
        <div class="d-flex flex-column align-items-start mb-2 w-100">
            <span class="bg-secondary text-white py-1 px-3 mw-100 chat-bubble-receive">Hello! How may I help you?</span>
        </div>
    </div>
</div>

<div id="messageDock" data-user="{{ "{} {}".format(g.user['first_name'], g.user['last_name']) }}" data-id="{{ g.user['id'] }}" class="d-block bg-dark w-100 p-2">
    <form action="{{ url_for('site.message') }}" onsubmit="send_message(event)">
    <div class="row justify-content-around align-items-center">
        <div class="col-8 col-md-10 form-group mb-0">
            <input id="messageBox" type="text" class="custom-input-text form-control" name="message" required>
        </div>
        <div class="col-4 col-md-2 text-center">
            <button class="btn btn-success">
                <i class="fa fa-paper-plane"></i> Send
            </button>
        </div>
    </div>
    </form>
</div>

</div>
</div>
{% endblock %}

{% block script %}
{{ super() }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.0/socket.io.js"></script>
<script>
    var socket = io.connect(`${window.location.origin}/chat`);
    
    socket.on('deliver message', function(data) {
        $('#inbox').append(`
            <div class="d-flex flex-column align-items-start mb-2 w-100">
                <span class="bg-secondary text-white py-1 px-3 mw-100 chat-bubble-receive">${data['message']}</span>
            </div>
        `);
    });

    socket.on('connect', function() {
        socket.emit('join', {id: $('#messageDock').attr('data-id')});
    });

    function send_message(e) {
        e.preventDefault();

        if($.trim($('#messageBox').val()) == '') {
            return;
        }

        var data = {};
        data['message'] = $('#messageBox').val();
        data['id'] = $('#messageDock').attr('data-id');
        data['sender'] = $('#messageDock').attr('data-user');

        socket.emit('send message', data, function() {
            $('#inbox').append(`
                <div class="d-flex flex-column align-items-end mb-2 w-100">
                    <span class="bg-warning py-2 px-3 mw-100 chat-bubble-send">${$('#messageBox').val()}</span>
                </div>
            `);
            $('#messageBox').val('');
        });
    }
</script>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block background %}{{ url_for('static', filename='img/bg/3.jpg') }}{% endblock %}

{% block title %} | Speaker Profile{% endblock %}

{% block nav_title %}Profile{% endblock %}

{% block return_link %}{{ url_for('site.speakers') }}{% endblock %}

{% block content %}
<div class="container">
    <div class="card border-0 bg-success text-white shadow mb-3">
        <img src="{{ speaker['img'] }}" alt="Speaker" class="card-img-top">
        <div class="card-body bg-light text-dark">
            <h5 class="card-title font-weight-bold">{{ speaker['name'] }}</h5>
            <h6 class="card-subtitle text-muted mb-2">{{ speaker['description'] }}</h6>
            <ul class="card-text">
                {% for i in speaker['summary'] %}
                <li>{{ i }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-footer">
            <a href="{{ url_for('site.speakers') }}" class="btn btn-block btn-warning text-uppercase">Go back</a>
        </div>
    </div>
</div>
{% endblock %}

templates/speakers.html
{% extends 'base.html' %}

{% block background %}{{ url_for('static', filename='img/bg/3.jpg') }}{% endblock %}

{% block title %} | Speakers{% endblock %}

{% block nav_title %}Speakers{% endblock %}

{% block content %}
<div class="container">
    <div class="row align-items-stretch">
        {% for i in speaker %}
        <div class="col-12 col-md-6 mb-3 ">
            <div class="card bg-success text-white shadow h-100">
                <img src="{{ i['img'] }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">{{ i['name'] }}</h5>
                    <h6 class="card-subtitle text-light mb-3">{{ i['description'] }}</h6>
                    <a href="{{ i['link'] }}" class="btn btn-warning btn-block text-uppercase">View Profile</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}